In [1]:
import numpy as np

In [3]:
uno = np.array([2, 6, 8])
due = np.array([9, 5, 6])

In [4]:
uno, due

(array([2, 6, 8]), array([9, 5, 6]))

In [ ]:
print(f'Somma: {uno + due}')

somma [11 11 14]


In [8]:
print(f'Prodotto: {uno * due}')

Prodotto: [18 30 48]


In [10]:
print(f'Elevazione al quadrato: {uno ** 2}')

Elevazione al quadrato: [ 4 36 64]


In [11]:
print(f'Prodotto scalare: {np.dot(uno, due)}')

Prodotto scalare: 96


In [ ]:
# Stipendi
salario_gio = [3000, 2800, 2600, 3000, 2500]
salario_val = [3300, 2900, 2800, 3100, 2320]
salario_mar = [8500, 1800, 6600, 8000, 2530]

In [13]:
riep_salari = np.array([salario_gio, salario_mar, salario_val])
riep_salari

array([[3000, 2800, 2600, 3000, 2500],
       [8500, 1800, 6600, 8000, 2530],
       [3300, 2900, 2800, 3100, 2320]])

In [15]:
# Bonus
bonus_gio = [100, 800, 600, 200, 500]
bonus_val = [300, 900, 800, 100, 320]
bonus_mar = [500, 800, 600, 200, 530]

In [17]:
riep_bonus = np.array([bonus_gio, bonus_mar, bonus_val])
riep_bonus

array([[100, 800, 600, 200, 500],
       [500, 800, 600, 200, 530],
       [300, 900, 800, 100, 320]])

In [ ]:
# Operazioni semplici tra matrici np, +
riepilogo = riep_salari + riep_bonus
riepilogo

array([[3100, 3600, 3200, 3200, 3000],
       [9000, 2600, 7200, 8200, 3060],
       [3600, 3800, 3600, 3200, 2640]])

In [21]:
# Operazioni semplici tra matrici np, *
riepilogo = riep_salari * riep_bonus
riepilogo

array([[ 300000, 2240000, 1560000,  600000, 1250000],
       [4250000, 1440000, 3960000, 1600000, 1340900],
       [ 990000, 2610000, 2240000,  310000,  742400]])

In [19]:
type(riepilogo)

numpy.ndarray

In [22]:
# Funzioni statistiche
riepilogo.max()

np.int64(4250000)

In [24]:
np.amax(riepilogo, axis=0)

array([4250000, 2610000, 3960000, 1600000, 1340900])

In [27]:
np.amax(riepilogo, axis=1)

array([2240000, 4250000, 2610000])