## Esercizio 14
* Crea una matrice 5×5 casuale.
* Trasponila e confronta se è simmetrica.
* Rendi la matrice simmetrica forzatamente e calcola la media dei valori sopra la diagonale.

In [1]:
import numpy as np

In [7]:
v1 = np.random.randint(0, 11, (5,5))
v1

array([[ 5,  2,  7,  1,  6],
       [ 0,  9, 10,  1,  5],
       [ 0,  1,  5,  6,  2],
       [ 0,  2,  4,  6,  9],
       [ 2,  8,  4,  4,  3]], dtype=int32)

In [10]:
v_T = v1.T
v_T

array([[ 5,  0,  0,  0,  2],
       [ 2,  9,  1,  2,  8],
       [ 7, 10,  5,  4,  4],
       [ 1,  1,  6,  6,  4],
       [ 6,  5,  2,  9,  3]], dtype=int32)

In [11]:
verifica = np.allclose(v1, v_T)
verifica

False

In [12]:
v_sym = (v1 + v_T) / 2
v_sym

array([[5. , 1. , 3.5, 0.5, 4. ],
       [1. , 9. , 5.5, 1.5, 6.5],
       [3.5, 5.5, 5. , 5. , 3. ],
       [0.5, 1.5, 5. , 6. , 6.5],
       [4. , 6.5, 3. , 6.5, 3. ]])

In [14]:
media_dia = v_sym[np.triu_indices(5, k=1)]
media = np.mean(media_dia)
media

np.float64(3.7)