## Esericizio 4
Genera 30 numeri equispaziati tra 0 e 10.
Rimodella l’array in una matrice 5×6.
Calcola la media e la deviazione standard per ogni colonna.

In [23]:
import numpy as np

In [24]:
v1 = np.linspace(0, 11, 30)
v1

array([ 0.        ,  0.37931034,  0.75862069,  1.13793103,  1.51724138,
        1.89655172,  2.27586207,  2.65517241,  3.03448276,  3.4137931 ,
        3.79310345,  4.17241379,  4.55172414,  4.93103448,  5.31034483,
        5.68965517,  6.06896552,  6.44827586,  6.82758621,  7.20689655,
        7.5862069 ,  7.96551724,  8.34482759,  8.72413793,  9.10344828,
        9.48275862,  9.86206897, 10.24137931, 10.62068966, 11.        ])

In [25]:
v1 = v1.reshape((5,6))
v1

array([[ 0.        ,  0.37931034,  0.75862069,  1.13793103,  1.51724138,
         1.89655172],
       [ 2.27586207,  2.65517241,  3.03448276,  3.4137931 ,  3.79310345,
         4.17241379],
       [ 4.55172414,  4.93103448,  5.31034483,  5.68965517,  6.06896552,
         6.44827586],
       [ 6.82758621,  7.20689655,  7.5862069 ,  7.96551724,  8.34482759,
         8.72413793],
       [ 9.10344828,  9.48275862,  9.86206897, 10.24137931, 10.62068966,
        11.        ]])

In [26]:
media = np.mean(v1, axis=0)
media

array([4.55172414, 4.93103448, 5.31034483, 5.68965517, 6.06896552,
       6.44827586])

In [27]:
deviazione_standard = np.std(v1, axis=0)
deviazione_standard

array([3.218555, 3.218555, 3.218555, 3.218555, 3.218555, 3.218555])