## Esercizio 5
Crea due array casuali 4×4 (valori interi tra 0 e 20).
Calcola la somma, differenza, prodotto elemento per elemento e divisione.
Trova gli indici dei valori maggiori nella differenza.

In [27]:
import numpy as np

In [28]:
v1 = np.random.randint(0, 21, (4,4))
v2 = np.random.randint(0, 21, (4,4))

In [29]:
somma = np.add(v1, v2)
somma

array([[11, 26, 28, 27],
       [29, 17,  7,  9],
       [22, 14, 25, 29],
       [27, 23, 27, 39]], dtype=int32)

In [30]:
differenza = np.subtract(v1, v2)
differenza

array([[ -1,   0, -12,   1],
       [ -7, -11,   5,  -9],
       [ 12,  -8, -11,   9],
       [ -5,  -9,  -1,   1]], dtype=int32)

In [31]:
indici_max = np.argmax(differenza)
indici_max

np.int64(8)

In [32]:
prodotto = np.multiply(v1, v2)
prodotto

array([[ 30, 169, 160, 182],
       [198,  42,   6,   0],
       [ 85,  33, 126, 190],
       [176, 112, 182, 380]], dtype=int32)

In [33]:
divisione = np.divide(v1,v2) 
divisione

array([[0.83333333, 1.        , 0.4       , 1.07692308],
       [0.61111111, 0.21428571, 6.        , 0.        ],
       [3.4       , 0.27272727, 0.38888889, 1.9       ],
       [0.6875    , 0.4375    , 0.92857143, 1.05263158]])