## Esercizio 13
* Genera una matrice quadrata 4×4 casuale.
* Calcola il determinante e verifica se la matrice è invertibile.
* Se sì, calcola la matrice inversa e verifica la correttezza tramite `A @ A_inv ≈ I`.


In [6]:
import numpy as np

In [7]:
v1 = np.random.randint(0, 11, (4,4))
v1

array([[10,  8,  9,  5],
       [10,  3,  9,  7],
       [ 4,  8,  7,  0],
       [ 9,  6,  5,  1]], dtype=int32)

In [8]:
determinante = np.linalg.det(v1)
determinante

np.float64(689.0000000000001)

In [13]:
if determinante != 0:
    print("La matrice è invertibile.")
    
    inv = np.linalg.inv(v1)
    print(f"La matrice inversa: {inv}")
    
    controllo = v1 @ inv
    print(f"controlla del inversa: \n{controllo}")
    
    print(f"LA verivica: {np.allclose(controllo, np.eye(4))}")
    
else:
    print("La matrice NON è invertibile.")

La matrice è invertibile.
La matrice inversa: [[-0.09433962  0.03773585 -0.0754717   0.20754717]
 [ 0.38751814 -0.26269956 -0.08998549 -0.09869376]
 [-0.38896952  0.27866473  0.28882438 -0.00580552]
 [ 0.46879536 -0.15674891 -0.22496372 -0.2467344 ]]
controlla del inversa: 
[[ 1.00000000e+00  1.11022302e-16 -8.32667268e-17  1.66533454e-16]
 [ 3.33066907e-16  1.00000000e+00 -2.49800181e-16  5.55111512e-17]
 [ 3.33066907e-16  5.55111512e-17  1.00000000e+00  1.14491749e-16]
 [ 6.66133815e-16 -1.66533454e-16 -4.16333634e-16  1.00000000e+00]]
LA verivica: True
