## Esercizio 17
* Genera un array 100×3 di valori casuali (simulando 100 osservazioni di 3 variabili).
* Normalizza ciascuna colonna tra 0 e 1.
* Calcola la media e la deviazione standard delle colonne normalizzate.

In [1]:
import numpy as np

In [ ]:
v1 = np.random.rand(100, 3)
v1

In [8]:
min_vals = v1.min(axis=0)
max_vals = v1.max(axis=0)

In [9]:
v_norm = (v1 - min_vals) / (max_vals - min_vals)
v_norm

array([[7.69538462e-01, 4.02634470e-02, 5.76180059e-01],
       [3.25787151e-01, 5.71561338e-02, 2.30842389e-01],
       [1.08135002e-01, 8.22233271e-01, 1.23199820e-01],
       [8.54958244e-01, 6.86111327e-01, 3.05633154e-01],
       [1.78113208e-03, 7.35336910e-01, 8.23362583e-01],
       [5.11099370e-01, 5.60330558e-01, 5.19634451e-01],
       [8.36490632e-02, 1.63920740e-02, 2.36725362e-01],
       [4.67350492e-01, 8.80349488e-01, 9.75331196e-01],
       [7.01646601e-01, 7.94558437e-01, 8.90719804e-01],
       [2.79992710e-01, 6.11751970e-01, 1.15839798e-01],
       [6.01554440e-01, 9.47944830e-01, 2.29591865e-01],
       [2.57238806e-01, 7.55765397e-01, 7.34065138e-01],
       [3.60367540e-02, 3.63608751e-01, 2.76552680e-01],
       [4.57724780e-01, 1.82192274e-01, 2.04143744e-01],
       [1.40799779e-01, 7.94559461e-02, 9.64177788e-01],
       [3.14146382e-01, 1.84885294e-01, 4.60244412e-01],
       [1.52744990e-01, 6.54897800e-01, 7.52800257e-02],
       [1.90268275e-01, 9.61667

In [10]:
mean_vals = v_norm.mean(axis=0)
std_vals  = v_norm.std(axis=0)
mean_vals, std_vals

(array([0.45812112, 0.51236531, 0.51498427]),
 array([0.28602905, 0.2832483 , 0.29885182]))