## Esercizio 16
* Crea un array 5×5 con valori da 0 a 24.
* Sottrai un vettore riga di lunghezza 5 ai valori della matrice.
* Verifica come NumPy gestisce il broadcasting e mostra il risultato.

In [1]:
import numpy as np

In [8]:
v1 = np.arange(0, 25).reshape(5,5)
v1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
v2 = np.array([0,1,2,3,4])
v2

array([0, 1, 2, 3, 4])

In [10]:
risultato = v1 - v2
risultato

array([[ 0,  0,  0,  0,  0],
       [ 5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10],
       [15, 15, 15, 15, 15],
       [20, 20, 20, 20, 20]])