## Esercizio 3 
Crea un array 6×6 di zeri e riempi la diagonale principale e secondaria con 1.
Somma tutti gli elementi della matrice e stampa il risultato.

In [18]:
import numpy as np

In [ ]:
diagonale_prin = np.eye(6)
diagonale_prin

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
diagonale_seco = np.fliplr(np.eye(6))
diagonale_seco

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [ ]:
tot_diago = np.array(diagonale_prin + diagonale_seco)
tot_diago

array([[1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [26]:
somma = np.sum(tot_diago)
print("\nSomma di tutti gli elementi:", somma)


Somma di tutti gli elementi: 12.0
