## Esercizio 11
* Crea un array casuale di 20 numeri float.
* Ordina l’array in ordine decrescente.
* Trova la posizione del 3° valore più grande e sostituiscilo con la media di tutti i valori.

In [2]:
import numpy as np

In [3]:
v1 = np.random.random(size=20)
v1

array([0.26132831, 0.61087421, 0.07123758, 0.61941631, 0.5512018 ,
       0.02883479, 0.3460921 , 0.18697258, 0.6869236 , 0.77737764,
       0.96198852, 0.08095596, 0.33650266, 0.96467574, 0.46075909,
       0.76255049, 0.89915574, 0.17974145, 0.67439622, 0.99520569])

In [6]:
ordina = np.sort(v1)[::-1]
ordina

array([0.99520569, 0.96467574, 0.96198852, 0.89915574, 0.77737764,
       0.76255049, 0.6869236 , 0.67439622, 0.61941631, 0.61087421,
       0.5512018 , 0.46075909, 0.3460921 , 0.33650266, 0.26132831,
       0.18697258, 0.17974145, 0.08095596, 0.07123758, 0.02883479])

In [7]:
terzo_valore = ordina[2]
terzo_valore

np.float64(0.9619885155359014)

In [8]:
posizione = np.where(v1 == terzo_valore)[0][0]
posizione

np.int64(10)

In [12]:
media = np.mean(v1)
v1[posizione] = media
v1

array([0.26132831, 0.61087421, 0.07123758, 0.61941631, 0.5512018 ,
       0.02883479, 0.3460921 , 0.18697258, 0.6869236 , 0.77737764,
       0.49969773, 0.08095596, 0.33650266, 0.96467574, 0.46075909,
       0.76255049, 0.89915574, 0.17974145, 0.67439622, 0.99520569])