## Esercizio 8 
* Crea un array di float casuali (10 elementi).
* Converti l’array in interi e confronta le differenze di valore.
* Calcola l’errore medio assoluto tra i due array.

In [15]:
import numpy as np

In [16]:
v1 = np.random.rand(10)
v1

array([0.25926308, 0.97098814, 0.1388532 , 0.8675011 , 0.12642705,
       0.55107278, 0.63665681, 0.99550846, 0.35075089, 0.95861016])

In [17]:
v1_int = v1.astype('i4')
v1_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [18]:
differenza = np.subtract(v1, v1_int)
differenza

array([0.25926308, 0.97098814, 0.1388532 , 0.8675011 , 0.12642705,
       0.55107278, 0.63665681, 0.99550846, 0.35075089, 0.95861016])

In [19]:
errore_medio_assoluto = np.mean(np.abs(differenza))
errore_medio_assoluto

np.float64(0.5855631675892988)