## Esercizo 20
* Genera una matrice 8×8 con numeri casuali tra 0 e 1.
* Calcola: media globale, somma per riga, valore minimo e massimo per colonna.
* Crea un array con la posizione dell’elemento massimo globale.


In [40]:
import numpy as np

In [41]:
v1 = np.random.uniform(0, 1, (8,8))
v1

array([[0.80952962, 0.11147637, 0.12920676, 0.29605479, 0.46287023,
        0.27799322, 0.61915085, 0.10877539],
       [0.77917027, 0.73357555, 0.73139246, 0.44919559, 0.16110908,
        0.69179726, 0.6466163 , 0.61572407],
       [0.10285831, 0.68317556, 0.73034446, 0.8600727 , 0.97067919,
        0.42336872, 0.12041754, 0.76428164],
       [0.06167078, 0.89253214, 0.42602005, 0.87311047, 0.37113167,
        0.48504477, 0.80716112, 0.73838574],
       [0.12170115, 0.76793696, 0.33497382, 0.06948057, 0.48637582,
        0.47906142, 0.56188764, 0.83604415],
       [0.90363573, 0.98917866, 0.38106889, 0.18421312, 0.12940467,
        0.15872918, 0.13964982, 0.61867607],
       [0.08248045, 0.52648299, 0.21654259, 0.70707089, 0.92889545,
        0.21154404, 0.34924888, 0.43899929],
       [0.55580373, 0.11143597, 0.25377595, 0.03499272, 0.63406304,
        0.2118315 , 0.2228387 , 0.51057062]])

In [42]:
media = np.mean(v1)
media

np.float64(0.4701951114142523)

In [43]:
somma_riga = np.sum(v1, axis=1)
somma_riga

array([2.81505722, 4.80858058, 4.65519812, 4.65505674, 3.65746152,
       3.50455614, 3.46126459, 2.53531222])

In [44]:
valore_mass = np.max(v1, axis=0)
valore_mass

array([0.90363573, 0.98917866, 0.73139246, 0.87311047, 0.97067919,
       0.69179726, 0.80716112, 0.83604415])

In [45]:
valore_mini= np.min(v1, axis=0)
valore_mini

array([0.06167078, 0.11143597, 0.12920676, 0.03499272, 0.12940467,
       0.15872918, 0.12041754, 0.10877539])

In [46]:
indice_massimo_globale = np.unravel_index(np.argmax(v1), v1.shape)
indice_massimo_globale

(np.int64(5), np.int64(1))