## Esercizio 6
* Crea una matrice 6×6 con valori da 0 a 35.
* Estrai la sottomatrice 3×3 centrale.
* Modifica gli elementi della prima colonna in 999 e stampa la matrice aggiornata.

In [ ]:
import numpy as np

In [8]:
v1 = np.arange(0, 36).reshape((6, 6))
v1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [15]:
v2 = v1[1:5, 1:5]
v2

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28]])

In [16]:
v1[:, 0] = 999
v1

array([[999,   1,   2,   3,   4,   5],
       [999,   7,   8,   9,  10,  11],
       [999,  13,  14,  15,  16,  17],
       [999,  19,  20,  21,  22,  23],
       [999,  25,  26,  27,  28,  29],
       [999,  31,  32,  33,  34,  35]])