## Esercizio 18
* Genera una matrice quadrata 3×3 casuale.
* Calcola gli autovalori e autovettori.
* Verifica la relazione `A @ v = λv` per ciascuna coppia.

In [1]:
import numpy as np

In [7]:
v1 = np.random.uniform(0, 11, (3,3))
v1

array([[ 0.62500743,  0.35780679,  6.87119231],
       [ 7.2069235 ,  6.1440864 ,  4.92511416],
       [10.77766974,  3.85955412,  3.97504488]])

In [8]:
autovalori, autovettori = np.linalg.eig(v1)
autovalori, autovettori

(array([14.08287064, -6.21504234,  2.87631041]),
 array([[-0.33987071, -0.70577383,  0.31926645],
        [-0.69893075,  0.1343668 , -0.9351828 ],
        [-0.62927236,  0.69557808,  0.15330386]]))

In [ ]:
print("\nVerifica v1 @ v = λ v:\n")
for i in range(len(autovalori)):
    λ = autovalori[i]
    v = autovettori[:, i]
    
    left = v1 @ v                  
    right = λ * v              

    print(f"Autovalore λ{i+1} = {λ}")
    print("v1 @ v  =", left)
    print("λ * v  =", right)
    print("Differenza = ", left - right)
    print("-" * 40)


Verifica v1 v = λ v:

Autovalore λ1 = 14.08287063613772
A @ v  = [-4.78635529 -9.84295136 -8.86196123]
λ * v  = [-4.78635529 -9.84295136 -8.86196123]
Differenza =  [-4.44089210e-15  1.77635684e-15  5.32907052e-15]
----------------------------------------
Autovalore λ2 = -6.2150423430460915
A @ v  = [ 4.38641423 -0.83509533 -4.32304723]
λ * v  = [ 4.38641423 -0.83509533 -4.32304723]
Differenza =  [3.55271368e-15 1.99840144e-15 8.88178420e-16]
----------------------------------------
Autovalore λ3 = 2.8763104052081108
A @ v  = [ 0.91830942 -2.689876    0.44094947]
λ * v  = [ 0.91830942 -2.689876    0.44094947]
Differenza =  [-1.11022302e-16  2.22044605e-15  1.60982339e-15]
----------------------------------------
