## Esercizio 15
* Crea una matrice 10×10 di zeri.
* Inserisci casualmente 10 valori diversi da zero.
* Conta quanti valori non nulli ci sono e sostituiscili con la loro radice quadrata.


In [13]:
import numpy as np

In [14]:
v1 = np.zeros((10,10))
v1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
valori_casuali = np.random.randint(1, 101, size=10)
valori_casuali

array([20, 80, 91, 23, 26, 94, 51, 14, 19, 95], dtype=int32)

In [16]:
righe = np.random.randint(0, 10, size=10)
colonne = np.random.randint(0, 10, size=10)

In [17]:
for i in range(10):
    v1[righe[i], colonne[i]] = valori_casuali[i]

print("\nMatrice con valori casuali inseriti:\n", v1)

non_zeri = np.count_nonzero(v1)
print("\nNumero di valori non nulli:", non_zeri)

v1[v1 != 0] = np.sqrt(v1[v1 != 0])
print("\nMatrice dopo la radice quadrata dei valori non nulli:\n", v1)


Matrice con valori casuali inseriti:
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 26.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 51.  0. 95.  0.  0.  0. 20.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 80.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 94.  0.  0.  0.  0.  0.  0.]
 [ 0. 19.  0.  0.  0.  0. 14.  0.  0.  0.]
 [23.  0.  0.  0.  0.  0.  0.  0.  0. 91.]]

Numero di valori non nulli: 10

Matrice dopo la radice quadrata dei valori non nulli:
 [[0.         0.         0.         0.         0.         0.
  0.         0.         0.         5.09901951]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         7.14142843 0.         9.74679434
  0.         0.         0.         4.47213595]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.  