In [3]:
#Esempio: Caricamento del dataset Iris
from sklearn.datasets import load_iris

# Carica il dataset Iris
iris = load_iris()

# Visualizza le chiavi disponibili nel dataset
print('le chiavi disponibili: ',iris.keys())

# Visualizza le prime 5 righe dei dati
print(iris.data[:5])

# Visualizza le etichette corrispondenti
print('le etichette corrispondenti: ',iris.target[:5])

le chiavi disponibili:  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
le etichette corrispondenti:  [0 0 0 0 0]


In [2]:
# Esempio: Generazione di un dataset di classificazione
from sklearn.datasets import make_classification

# Genera un dataset di classificazione
# n_samples: Numero totale di campioni da generare.
# n_features: Numero totale di feature (caratteristiche) da generare per ogni campione.
# n_informative: Numero di feature informative (devono essere <= n_features)
# n_redundant: Numero di feature ridondanti (combinazioni lineari di quelle informative)
# n_classes: Numero di classi nel dataset (problema di classificazione).
# random_state: Seme per garantire la riproducibilità dei risultati.
X, y = make_classification(n_samples=100, n_features=5, n_informative=3, n_redundant=1, n_classes=2, random_state=42)

# Visualizza le prime 5 righe dei dati
print("Prime 5 righe dei dati:")
print(X[:5])

# Visualizza le etichette corrispondenti
print("Prime 5 etichette:")
print(y[:5])

# Visualizza informazioni sul dataset
print(f"\nShape del dataset: {X.shape}")
print(f"Numero di classi: {len(set(y))}")
print(f"Distribuzione delle classi: {list(y).count(0)} classe 0, {list(y).count(1)} classe 1")

Prime 5 righe dei dati:
[[ 0.06561344 -1.81431652 -0.84853401  0.27872303 -1.89816218]
 [ 1.9436449  -0.7812514  -0.78040602 -1.02038325 -0.17664666]
 [ 2.21543669 -1.59145991 -1.7541757  -0.15772396  0.8755859 ]
 [ 2.24889649  1.43883123  1.07127592  0.16608813 -0.73306457]
 [ 1.39888763  1.60328098  1.30729431 -2.4522646  -0.76359582]]
Prime 5 etichette:
[0 1 1 1 0]

Shape del dataset: (100, 5)
Numero di classi: 2
Distribuzione delle classi: 50 classe 0, 50 classe 1


In [4]:
# Esempio: Generazione di un dataset di regressione
from sklearn.datasets import make_regression

# Genera un dataset di regressione
X, y = make_regression(n_samples=200, n_features=3, noise=0.2, random_state=42)

# Visualizza le prime 5 righe dei dati
print("Prime 5 righe dei dati:")
print(X[:5])

# Visualizza le etichette corrispondenti
print("Prime 5 etichette:")
print(y[:5])

# Visualizza informazioni sul dataset
print(f"\nShape del dataset: {X.shape}")
print(f"Media delle etichette: {y.mean():.2f}")

Prime 5 righe dei dati:
[[ 0.13074058 -1.43014138 -0.44004449]
 [ 1.50235705 -0.26940683  0.71754226]
 [ 0.64768854  0.49671415 -0.1382643 ]
 [ 0.34175598 -0.75913266  0.15039379]
 [ 0.85639879 -1.51484722 -0.44651495]]
Prime 5 etichette:
[-55.34280021 153.84274546  48.31418843  18.03506629  -5.84576917]

Shape del dataset: (200, 3)
Media delle etichette: -6.03


In [6]:
# Esempio: Generazione di un dataset di clustering
from sklearn.datasets import make_blobs

# Genera un dataset di clustering
X, y = make_blobs(n_samples=100, centers=3, random_state=42)

# Visualizza le prime 5 righe dei dati
print('le prime 5 righe: ',X[:5])

# Visualizza le etichette corrispondenti
print('le etichette corrispondenti: ',y[:5])

le prime 5 righe:  [[-7.72642091 -8.39495682]
 [ 5.45339605  0.74230537]
 [-2.97867201  9.55684617]
 [ 6.04267315  0.57131862]
 [-6.52183983 -6.31932507]]
le etichette corrispondenti:  [2 1 0 1 2]


In [7]:
# Esempio: Standardizzazione con StandardScaler
from sklearn.preprocessing import StandardScaler

# Crea dati di esempio
import numpy as np
data = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]]) #[-100, -1000, -10000], , [1500, 2000, 2500]

# Applica la standardizzazione
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [8]:
# Esempio: Normalizzazione con MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# Applica la normalizzazione
# Fromula x' = (x - min(x)) / (max(x) - min(x))
minmax_scaler = MinMaxScaler()
normalized_data = minmax_scaler.fit_transform(data)

print(normalized_data)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [12]:
# Esempio: One-Hot Encoding con OneHotEncoder
#La codifica delle variabili categoriche è 
#essenziale per convertire dati non numerici in un formato 
#utilizzabile dagli algoritmi di machine learning.
from sklearn.preprocessing import OneHotEncoder

# Crea dati categorici di esempio
categories = np.array([['red'], ['blue'], ['green']])
#print(categories)

# Applica la codifica one-hot
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(categories).toarray()

print(encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [13]:
# Esempio: Imputazione con SimpleImputer
from sklearn.impute import SimpleImputer

# Crea dati con valori mancanti
data_with_nan = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

# Applica l'imputazione
imputer = SimpleImputer(strategy='mean')
imputed_data = imputer.fit_transform(data_with_nan)

print(imputed_data)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]
