<img src="https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png" alt="350" width="400" align="left"/>

<h2> Cos'è NumPy? </h2>

<ul>

<li>NumPy è una libreria Python utilizzata per lavorare con gli array.</li>

<li>Dispone anche di funzioni per lavorare nel dominio dell'algebra lineare, della trasformata di Fourier e delle matrici.</li>

<li>NumPy è stato creato nel 2005 da Travis Oliphant. È un progetto open source e puoi usarlo liberamente.</li>

<li>NumPy sta per Python numerico.</li>
<li>NumPy è una libreria Python ed è scritta parzialmente in Python, ma la maggior parte delle parti che richiedono calcoli veloci sono scritte in C o C++.</li>
</ul>

<h2>Perché usare NumPy?</h2>
<ul>
<li>In Python abbiamo elenchi che servono allo scopo di array, ma sono lenti da elaborare.</li>

<li>NumPy mira a fornire un oggetto array fino a 50 volte più veloce rispetto ai tradizionali elenchi Python.</li>

<li>L'oggetto array in NumPy si chiama ndarray e fornisce molte funzioni di supporto che rendono molto semplice lavorare con ndarray.</li>

<li>Gli array vengono utilizzati molto frequentemente nella scienza dei dati, dove la velocità e le risorse sono molto importanti.</li>
</ul>

## Numpy Ndarray

<img src="https://miro.medium.com/max/831/1*R0wH6D43-rzG7ivvEhSFkA.png" alt="500" width="600" align="left"/>

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\Roman\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np #import numpy library

In [3]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d array

arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [4]:
print(arr_1d)

[1 2 3 4 5]


In [5]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Tipi di dati numpy più importanti
<table >
<thead>
<tr ><th ><p>Tipi Numpy</p></th>
<th><p>Relativi tipi Python</p></th>

</tr>
</thead>
<tbody>
<tr><td><p><a href="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.int_" title="numpy.int_"><code ><span>	int_, int8, int16, int32, int64, uint8, uint16, uint32, uint64</span></code></a></p></td>
<td><p><a href="https://docs.python.org/3/library/functions.html#int" ><code><span >int</span></code></a></p></td>
</tr>
<tr><td><p><a href="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.double"><code><span>double</span></code></a></p></td>
<td><p><a href="https://docs.python.org/3/library/functions.html#float" ><code><span >float</span></code></a></p></td>
</tr>
<tr><td><p><a  href="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bytes_" title="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bytes_"><code><span class="pre">bytes_</span></code></a></p></td>
<td><p><a href="https://docs.python.org/3/library/stdtypes.html#bytes"><code ><span >bytes</span></code></a></p></td>
</tr>
<tr><td><p><a href="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.str_" ><code ><span >str_</span></code></a></p></td>
<td><p><a href="https://docs.python.org/3/library/stdtypes.html#str" ><code ><span>str</span></code></a></p></td>
</tr>
<tr><td><p><a  href="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bool_" ><code ><span >bool_</span></code></a></p></td>
<td><p><a  href="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bool" ><code ><span >bool</span></code></a></p></td>
</tr>
<tr ><td><p><a  href="https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.datetime64" ><code ><span >datetime64</span></code></a></p></td>
<td><p><a  href="https://docs.python.org/3/library/datetime.html#datetime.datetime" ><code ><span class="pre">datetime.datetime</span></code></a></p></td>
</tr>
</tbody>
</table>

**1D Array Operations:**

In [6]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d array

In [7]:
arr_1d.ndim #1d array -> 1 dimension

1

In [8]:
arr_1d.size #number of elements

5

In [9]:
arr_1d.min()

np.int64(1)

In [10]:
arr_1d.max()

np.int64(5)

In [11]:
arr_1d.sum()

np.int64(15)

In [12]:
np.arange(4) #array with range of numbers [0,4(not included)]

array([0, 1, 2, 3])

In [13]:
np.arange(0,11,2) #stepover

array([ 0,  2,  4,  6,  8, 10])

In [14]:
#Restituisce numeri equidistanti in un intervallo specificato:

np.linspace(0, 10, 5, dtype=float) #(stop number included in this case)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**2D Array Operations (MATRIX):**

In [15]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4]]) #2d array -> matrix

In [16]:
arr_2d.ndim #2d array (matrix) -> 2 dimensions

2

In [17]:
arr_2d.size #number of elements

16

In [18]:
arr_2d.shape #m rows, n columns (mxn)

(4, 4)

In [19]:
arr_2d.min()

np.int64(1)

In [20]:
arr_2d.max()

np.int64(12)

In [21]:
arr_2d.sum()

np.int64(88)

In [22]:
arr_2d.mean()

np.float64(5.5)

In [23]:
#Il valore mediano è il valore al centro, dopo aver ordinato tutti i valori:
np.median(arr_2d)

np.float64(4.5)

In [24]:
#Il valore Modale è il valore che appare il maggior numero di volte nell'array.
"""
Per poterlo calcolare abbiamo bisogno della libreria Scipy:

SciPy è una libreria di calcoli scientifici che utilizza NumPy come base.

SciPy sta per Scientific Python, fornisce più funzioni di utilità per l'ottimizzazione, 
le statistiche e l'elaborazione del segnale.

Come NumPy, SciPy è open source, quindi possiamo usarlo liberamente.

SciPy è stato creato dal creatore di NumPy Travis Olliphant.
"""
from scipy import stats

stats.mode(arr_2d)


ModeResult(mode=array([1, 2, 3, 4]), count=array([2, 2, 2, 2]))

<h1>Unire gli array NumPy</h1>
Unire significa mettere il contenuto di due o più array in un unico array.

In NumPy per unire gli array bidimensionali dobbiamo tenere conto degli assi.

Per unirli dobbiamo passare una sequenza di array alla funzione <u>concatenate()</u> e in non fosse unidimensionale anche l'asse. Se l'asse non viene passato esplicitamente, viene considerato come 0.

In [25]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [26]:
arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([[5, 6], 
                 [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


**Access Items:**

<img src="https://numpy.org/doc/stable/_images/np_matrix_indexing.png" alt="600" width="700" align="left"/>

In [28]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [29]:
#First element: first row/column (1)

arr_2d[0,0] # [row index, col index]

np.int64(1)

In [30]:
#Only first row

arr_2d[0, :] # same thing -> arr_2d[0]

array([1, 2, 3, 4])

In [31]:
#Only first column

arr_2d[:,0]

array([1, 5, 9])

**Useful Numpy Functions:**

<img src="https://numpy.org/doc/stable/_images/np_ones_zeros_matrix.png" width="700" align="left"/>

In [32]:
np.zeros(2) #1D  -> float numbers by default

array([0., 0.])

In [33]:
np.zeros(2, dtype=int) #with integer numbers

array([0, 0])

In [34]:
np.zeros((2,2)) #2D MATRIX

array([[0., 0.],
       [0., 0.]])

In [35]:
np.ones(2) #1D

array([1., 1.])

In [36]:
np.ones((2,2)) #2D MATRIX

array([[1., 1.],
       [1., 1.]])

In [37]:
np.full(2,3)

array([3, 3])

In [38]:
np.full((2,3),10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

In [39]:
np.random.random(3) #1D -> Return random floats in the half-open interval [0.0, 1.0]

array([0.65916895, 0.17361983, 0.48555259])

In [40]:
np.random.random((3,2)) #2D MATRIX

array([[0.70371985, 0.05761391],
       [0.21390868, 0.8529347 ],
       [0.38894355, 0.97365778]])

In [41]:
np.random.randint(0,100,(3,2)) #2D MATRIX

array([[35, 91],
       [91, 10],
       [98, 50]], dtype=int32)

<h1>Cos'è la deviazione standard?</h1>
La deviazione standard è un numero che descrive la distribuzione dei valori.

Una deviazione standard bassa significa che la maggior parte dei numeri sono vicini al valore medio (medio).

Una deviazione standard elevata significa che i valori sono distribuiti su un intervallo più ampio.

In [42]:
elements = np.random.randint(0,1000,(1,10))


x = np.std(elements)
print(elements)
print(x)

[[551 931 345 370 552 676 168 307 669 803]]
227.37009477941464


<h1>Cosa sono i percentili?</h1>

I percentili vengono utilizzati nelle statistiche per fornire un numero che descrive il valore a cui è inferiore una determinata percentuale dei valori.

Esempio: supponiamo di avere un array delle età di tutte le persone che vivono in una strada.
Qual è il 75° percentile? La risposta è 43, il che significa che il 75% delle persone ha 43 anni o meno.

In [43]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

x = np.percentile(ages, 75)

print(x)

43.0


<img src="https://www.w3resource.com/w3r_images/numpy-array-eye-function-image-1-b.png" width="200" align="left"/>

In [44]:
np.eye(2) #IDENTITY MATRIX 3x3

array([[1., 0.],
       [0., 1.]])

**Reshape Array (modificare dimensioni): Gives a new shape to an array without changing its data.**

<img src="https://numpy.org/doc/stable/_images/np_reshape.png" width="600" align="left"/>

In [45]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2D ARRAY 3X4

In [46]:
arr_2d_res = arr_2d.reshape(4,3) #2D ARRAY 4X3
print(arr_2d_res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Boolean Indexing**:

In [47]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d array

In [48]:
print(arr_1d < 3) #RETURN BOOLEAN VALUES

[ True  True False False False]


In [49]:
print(arr_1d[arr_1d < 3]) #FILTER: RETURN ARRAY ELEMENTS THAT MEET THE CONDITION

[1 2]


In [50]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [51]:
print(arr_2d < 3)

[[ True  True False False]
 [False False False False]
 [False False False False]]


In [52]:
print(arr_2d[arr_2d < 3])

[1 2]


In [53]:
np.where(arr_2d < 4, 1, 0) #if True -> 1 else 0

array([[1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**Perché Numpy Array è così veloce?:**

In [54]:
# ndarray 2D di forma (10000, 10000) con float casuale nell'intervallo [0, 1]. Sono 100 milioni di numeri!
A = np.random.rand(10000, 10000) #RANDOM RAND: crea un array della forma data e popolalo con campioni casuali da una distribuzione uniforme su [0, 1].
a = A.tolist()

In [55]:
%%time
total = 0
for row in a:
    for n in row:
        total += n
round(total, 2)

CPU times: total: 18.1 s
Wall time: 1min 29s


49996440.3

In [56]:
%%time
round(np.sum(A), 2)

CPU times: total: 1.19 s
Wall time: 11.1 s


np.float64(49996440.3)

**Operazioni di algebra lineare:**

**1D ARRAY:**

In [57]:
#Array 1D operations

In [58]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [59]:
a+b #addition

array([5, 7, 9])

In [60]:
a-b #subtraction

array([-3, -3, -3])

In [61]:
a*3 #scalar multiplication

array([3, 6, 9])

In [62]:
#Prodotto scalare:

c= np.array([1,0]) 
d= np.array([0,1]) 

e= np.array([1,2,3])
f= np.array([2,4,6]) #combinazione lineare dell'array e (e*2)

#Dot product (prodotto scalare):

print(np.dot(c,d)) # =0 -> prodotto scalare =0, perpendicolari, angolo = 90°
print(np.dot(e,f)) # prodotto scalare positivo & !=0 -> angolo <90°

0
28


**Operazioni sulle MATRIX:**

In [63]:
#2D MATRIX OPERATIONS

In [64]:
M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])

#scalar multiplication

M_1 * 10

array([[10, 20],
       [30, 40]])

In [65]:
#ARITHMETIC OPERATIONS ON MATRICES 

M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])
      
M_2 = np.array([[5, 6],  #square matrix 2x2
                [7, 8]])

print(M_1 + M_2)

[[ 6  8]
 [10 12]]


In [66]:
#PRODOTTO MATRICIALE

M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])
      
M_2 = np.array([[5, 6],  #square matrix 2x2
                [7, 8]])

print(np.dot(M_1,M_2))   #OUTPUT : square matrix 2x2

[[19 22]
 [43 50]]


In [67]:
M_1= np.array([[1,2,3], #2x3
               [0,1,2]]) 

M_2= np.array([[4,5],   #3x2
               [6,7],
               [8,9]])

print(np.dot(M_1,M_2))  #OUTPUT square matrix: 2x2

[[40 46]
 [22 25]]


In [68]:
M_1 @ M_2 # @ -> another option

array([[40, 46],
       [22, 25]])

## <mark>Esercizio1</mark>
<h4>Create 2 array numpy:</h4>
<ul>
<li>Un array unidimensionale di numeri casuali compresi tra 0 e 1;</li>
<li>Un array bidimensionale di dimensione 3x3 con valori interi casuali.</li>
<ul>


## <mark>Esercizio2</mark>
<h4>Create 2 array bidimensionali numpy 4x4 con valori interi casuali ed eseguite le seguenti operazioni:</h4>
<ul>
<li>Restituite la somma di tutti gli elementi dei singoli array che si trovano nell'ultima riga dalla seconda colonna in poi;</li>
<li>Unite i 2 array secondo l'asse 1.</li>
<ul>


## <mark>Esercizio3</mark>
<h4>Create 1 array unidimensionale con 50 valori randomici compresi tra 1 e 1.000 e fate i seguenti calcoli:</h4>
<ul>
<li>Calcolo della media;</li>
<li>Calcolo della moda;</li>
<li>Calcolo della deviazione standard;</li>
<li>Trasformatelo in un array 5 X 10</li>
<ul>


# Sistema di equazioni lineari

Un sistema di equazioni lineari (o sistema lineare) è una raccolta di una o più equazioni lineari che coinvolgono lo stesso insieme di variabili.

<img src="https://miro.medium.com/max/1400/1*6LRv9DMK9hXvwm5JVpTQuA.png" alt="500" width="600" align="left"/>

In [69]:
#Abbiamo un chiosco allo stadio dove vendiamo:

#Gli hot dog costano 1,50€
#Coca Cola costa 0,50€
#Realizzato in totale €78,50
#Venduti 87 hot dog e Coca Cola insieme

#Quanti Hot Dog(x) e Coca Cola(y) sono stati venduti?

In [70]:
# 1.50x + 0.50y = 78.50 (Equazione relativa al costo)

# x + y = 87 (Equazione relativa al numero venduto)

In [71]:
a= np.array([[1.50, 0.5], #MATRICE COEFFICIENTI
             [1, 1]])

b= np.array([[78.50], #MATRICE TERMINI NOTI
              [87]])

In [72]:
#Calculate inverse of A

inv_a= np.linalg.inv(a)

In [73]:
ID= a @ inv_a  #identity matrix
ID

array([[1.00000000e+00, 1.11022302e-16],
       [2.22044605e-16, 1.00000000e+00]])

In [74]:
ID_2= np.eye(2)
ID_2

array([[1., 0.],
       [0., 1.]])

In [75]:
np.allclose(ID, ID_2) #confrontiamo le 2 matrici identità solo per sicurezza.

True

In [76]:
X= inv_a @ b #matrice delle Soluzioni (valori incognite)
X

array([[35.],
       [52.]])

In [77]:
#Built in function -> linalg.solve() -> DIRETTAMENTE MATRICE SOLUZIONI

np.linalg.solve(a, b)

array([[35.],
       [52.]])