## 1. sklearn.datasets: Caricamento e Generazione di Dataset

### Esercizio 1.1 (Base): Esplorazione Dataset Integrati
Carica il dataset Wine e analizza le sue caratteristiche principali.

In [1]:
# Esercizio 1.1: Carica il dataset Wine e rispondi alle seguenti domande:
# 1. Quanti campioni e feature contiene?
# 2. Quante classi ci sono?
# 3. Quali sono i nomi delle feature?
# 4. Visualizza le prime 3 righe dei dati


### Esercizio 1.2 (Intermedio): Generazione Dataset Personalizzato
Crea un dataset sintetico per un problema di classificazione con specifiche caratteristiche.

In [2]:
# Esercizio 1.2: Genera un dataset di classificazione con:
# - 500 campioni
# - 8 feature totali (4 informative, 2 ridondanti)
# - 3 classi
# - 2 cluster per classe
# Poi visualizza le statistiche di base del dataset creato

### Esercizio 1.3 (Avanzato): Confronto Dataset Reali vs Sintetici
Confronta le caratteristiche del dataset Diabetes con un dataset sintetico di regressione.

In [3]:
# Esercizio 1.3: 
# 1. Carica il dataset Diabetes
# 2. Crea un dataset sintetico di regressione con le stesse dimensioni
# 3. Confronta le statistiche (media, std, range) delle feature

## 2. sklearn.preprocessing: Preprocessing dei Dati

### Esercizio 2.1 (Base): Scalatura Dati
Applica diverse tecniche di scalatura sui dati del Wine dataset.

In [4]:
# Esercizio 2.1: Applica StandardScaler e MinMaxScaler al dataset Wine
# Confronta i risultati mostrando media e deviazione standard prima e dopo

### Esercizio 2.2 (Intermedio): Gestione Dati Mancanti
Crea e gestisci un dataset con valori mancanti usando diverse strategie di imputazione.

In [5]:
# Esercizio 2.2: 
# 1. Crea un array con valori mancanti (NaN) in posizioni casuali
# 2. Applica SimpleImputer con strategie: 'mean', 'median', 'most_frequent'
# 3. Confronta i risultati

## 3. sklearn.model_selection: Suddivisione Dati e Validazione

### Esercizio 3.1 (Base): Suddivisione Dati
Pratica la suddivisione dei dati con diverse proporzioni e analizza l'impatto.

In [6]:
# Esercizio 3.1: Usa il dataset Iris per sperimentare diverse suddivisioni
# Testa: 80-20, 70-30, 60-40 e osserva come cambia la distribuzione delle classi

### Esercizio 3.2 (Intermedio): Validazione Incrociata
Implementa diverse strategie di cross-validation e confronta i risultati.

In [7]:
# Esercizio 3.2: Applica cross-validation con diversi fold (3, 5, 10) 
# su un classificatore SVM usando il dataset Wine
# Confronta accuracy media e deviazione standard

### Esercizio 3.3 (Avanzato): Ottimizzazione Iperparametri
Confronta GridSearchCV e RandomizedSearchCV per ottimizzare un Random Forest.

In [8]:
# Esercizio 3.3: Ottimizza un Random Forest usando entrambi i metodi
# Confronta tempi di esecuzione e risultati ottenuti (best_params, best_score)



---

## 4. sklearn.decomposition: Riduzione Dimensionalità

### Esercizio 4.1 (Base): PCA Base
Applica PCA per ridurre la dimensionalità e visualizza la varianza spiegata.

In [9]:
# Esercizio 4.1: Applica PCA al dataset Digits
# 1. Riduci da 64 a 10 componenti
# 2. Visualizza la varianza spiegata cumulativa
# 3. Determina quante componenti servono per spiegare il 95% della varianza


In [10]:
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
import numpy as np

In [11]:
digits = load_digits()

In [12]:
data = digits.data
data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [13]:
# Applica PCA per ridurre la dimensionalità a 1 componente
pca = PCA(n_components=1)
reduced_data = pca.fit_transform(data)

print("Dati originali:", data)
print("Dati ridotti:", reduced_data)

Dati originali: [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
Dati ridotti: [[-1.25946645]
 [ 7.9576113 ]
 [ 6.99192297]
 ...
 [10.8012837 ]
 [-4.87210009]
 [-0.34438963]]


In [14]:
#Visualizza la varianza spiegata da ogni componente principale
print("Varianza spiegata:", pca.explained_variance_ratio_)

Varianza spiegata: [0.14890594]


In [15]:
pca_full = PCA().fit(X)
cumulative_variance = np.cumsum(pca_full.explained_varianceratio)
n_components_95 = np.argmax(cumulative_variance >= 0.95) + 1
print(f"✅ Componenti necessarie per spiegare il 95% della varianza: {n_components_95}")

NameError: name 'X' is not defined

### Esercizio 4.2 (Intermedio): Confronto Tecniche di Decomposizione
Confronta PCA, ICA e NMF sullo stesso dataset.

In [ ]:
# Esercizio 4.2: Confronta PCA, FastICA e NMF sul dataset Olivetti Faces
# Usa 10 componenti per tutti e confronta la ricostruzione

In [17]:
from sklearn.datasets import fetch_olivetti_faces
from sklearn.decomposition import PCA, FastICA, NMF

In [18]:
pca = PCA(n_components=10)
olivetti_data = fetch_olivetti_faces()
X = olivetti_data.data

reduced_data = pca.fit_transform(X)
reduced_data

array([[ 6.4326086 ,  0.7036647 , -1.4300263 , ...,  2.9378536 ,
        -0.37383553, -0.24339887],
       [ 1.0758938 ,  6.6973357 ,  1.8427855 , ...,  2.1007981 ,
        -1.0724928 , -2.0605724 ],
       [ 5.2929487 ,  1.5425119 ,  0.22595152, ...,  3.189259  ,
        -1.5654786 , -0.59941345],
       ...,
       [-2.0407658 ,  1.5096205 ,  3.4487293 , ..., -1.6931145 ,
        -2.7927284 ,  1.3973047 ],
       [ 5.1652355 , -8.0967655 , -0.6709978 , ..., -1.271197  ,
        -1.0892012 ,  1.1271701 ],
       [ 1.1505027 , -2.4350314 ,  1.1894976 , ...,  1.1087124 ,
         0.2332357 ,  1.6104105 ]], shape=(400, 10), dtype=float32)

In [19]:
# Applica ICA per estrarre componenti indipendenti
ica = FastICA(n_components=10, random_state=42)
independent_components = ica.fit_transform(data)

print("Componenti indipendenti:", independent_components)

Componenti indipendenti: [[ 0.11702961  0.74449381 -0.71517995 ...  0.92790214 -0.9426612
   0.42874276]
 [ 0.37834231 -0.45221233  0.24934179 ... -1.02087372  1.71155906
   0.62728642]
 [ 0.33072785  0.05923536 -1.99461641 ...  0.57452008  0.90908242
   2.22541888]
 ...
 [-0.53262413 -0.08581548 -0.36768602 ... -0.41363132  1.00905794
   2.02943282]
 [-0.11167468 -1.13388963 -0.80203755 ...  0.38970448 -0.38534028
  -0.38708528]
 [-1.45180803 -0.09363772  0.19572944 ... -0.37204547 -0.83822863
   0.94940152]]


In [20]:
# Applica NMF
nmf = NMF(n_components=10, random_state=42)
components = nmf.fit_transform(data)

print("Componenti NMF:", components)

Componenti NMF: [[0.         0.         0.         ... 0.00834253 0.38865555 0.33936691]
 [0.02515264 0.13542882 0.08807536 ... 0.35215399 0.19422037 0.        ]
 [0.13128854 0.12697322 0.         ... 0.18069419 0.00656905 0.        ]
 ...
 [0.02743425 0.12819272 0.04799984 ... 0.26979312 0.28937077 0.02244282]
 [0.10370016 0.         0.1018451  ... 0.05680721 0.38339828 0.19101747]
 [0.14301475 0.0789389  0.0730297  ... 0.05162946 0.15556497 0.40548038]]


C:\Users\Roman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\decomposition\_nmf.py:1728: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


### Esercizio 4.3 (Avanzato): Dimensionalità Ottimale
Determina la dimensionalità ottimale usando validazione incrociata.

In [ ]:
# Esercizio 4.3: Trova il numero ottimale di componenti PCA
# utilizzando un classificatore e cross-validation sul dataset Wine

In [22]:
from sklearn.datasets import load_wine

wine = load_wine()
X = wine.data
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], shape=(178, 13))