Create un programma che crea un dataframe sulla base dell'imput dell'utente contenente 4 studenti e le medie dei voti mensili per sei mesi di studio.
Il programma ci restituirà:
-Un grafico contenente 4 grafici più piccoli, uno per ogni studente, con andamento delle medie dei voti per ogni mese;
-Un altro grafico che racchiude tutti gli andamenti di tutti gli studenti

In [6]:
import pandas as pd
studenti = []

In [ ]:

for i in range(4): 
    print(f"\n--- Inserisci i dati per lo studente {i+1} ---")
    nome = input("Inserisci il nome: ")
    cognome = input("Inserisci il cognome: ")
    corso = input("Inserisci il corso: ")
    medie_mensili = {} 
    print(f"Inserisci le medie dei voti per 6 mesi per {nome} {cognome}:")
    
    for mese_num in range(1, 7): 
        while True: 
            voto_input = input(f"Media voto per il Mese {mese_num}: ")
            try:
                voto_numerico = float(voto_input)
                if 0 <= voto_numerico <= 10: 
                    medie_mensili[f'Mese {mese_num}'] = round(voto_numerico, 2) # Arrotonda a 2 decimali
                    break 
                else:
                    print("Voto non valido. Inserisci un numero tra 0 e 10.")
            except ValueError:
                print("Input non valido. Inserisci un numero.")
 
    dati_studente = {
        'Nome': nome,
        'Cognome': cognome,
        'Corso': corso,
        **medie_mensili 
        }
    studenti.append(dati_studente) 
df = pd.DataFrame(studenti)

print("\n--- DataFrame delle Medie Mensili ---")
print(df)
    


--- Inserisci i dati per lo studente 1 ---
Inserisci le medie dei voti per 6 mesi per fddf fdgdf:

--- Inserisci i dati per lo studente 2 ---
Inserisci le medie dei voti per 6 mesi per drfgdfg rd:

--- Inserisci i dati per lo studente 3 ---
Inserisci le medie dei voti per 6 mesi per hfh fgfgf:

--- Inserisci i dati per lo studente 4 ---
Inserisci le medie dei voti per 6 mesi per fhghf fgdf:

--- DataFrame delle Medie Mensili ---
      Nome Cognome    Corso  Mese 1  Mese 2  Mese 3  Mese 4  Mese 5  Mese 6
0     fddf   fdgdf  fdgdfgd     3.0     5.0     6.0     4.0     7.0     4.0
1  drfgdfg      rd      fgd     4.0     6.0     6.0     4.0     5.0     6.0
2      hfh   fgfgf      ffh     4.0     4.0     6.0     7.0     5.0     5.0
3    fhghf    fgdf      fgd     4.0     4.0     4.0     6.0     7.0     6.0


In [7]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.figure(figsize=(15, 10))
mesi_labels = [f'Mese {m}' for m in range(1, 7)]
x_values = np.arange(1, 7)

for i, student_data in enumerate(studenti):
    plt.subplot(2, 2, i + 1)
    y_values = [student_data[mese] for mese in mesi_labels]

    plt.plot(x_values, y_values, marker='o') 
    plt.title(f"Andamento Voti: {student_data['Nome']} {student_data['Cognome']}")
    plt.xlabel("Mese")
    plt.ylabel("Media Voto")
    plt.ylim(0, 10) 
    plt.xticks(x_values, mesi_labels, rotation=45, ha='right')
    plt.grid(True, linestyle='--', alpha=0.7)
plt.suptitle("Andamento Mensile delle Medie Voti per Studente", fontsize=16) 
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) 
plt.show()

<Figure size 1500x1000 with 0 Axes>

In [9]:
#Importa la libreria NumPy con l'alias np.
import numpy as np

In [ ]:
#Crea un array NumPy chiamato ar_interi contenente i numeri 
#interi da 0 a 9.
ar_interi = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar_interi)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Calcola la somma, la media e il prodotto degli elementi di 
#ar_interi e stampali.
print(ar_interi.sum())
print(ar_interi.mean())
print(ar_interi.prod())

45
4.5
0


In [ ]:
#Crea un altro array NumPy chiamato ar_decimali contenente 5 
#numeri decimali a tua scelta.
ar_decimali = np.array([10.4,11.7,12.4,13.7,14.2])
print(ar_decimali)

[10.4 11.7 12.4 13.7 14.2]


In [18]:
#Crea due array NumPy: a = np.array([10, 20, 30, 40]) e 
# b = np.array([1, 2, 3, 4]).
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

In [21]:
#Esegui la somma, la sottrazione, la moltiplicazione e 
#la divisione (reale, non intera) elemento per elemento 
# tra a e b. Stampa ogni risultato.
somm = a + b
print(somm)
sott = a - b
print(sott)
molt = a * b
print(molt)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


In [14]:
#Importa la libreria Pandas con l'alias pd.
import pandas as pd

In [16]:
#Crea una Serie Pandas chiamata età_studenti dai seguenti 
# dati: [20, 22, 21, 23, 20]. Assegna nomi personalizzati agli 
# indici, ad esempio: ['Alice', 'Bob', 'Charlie', 'Diana', 'Eva'].
età_studenti = [20, 22, 21, 23, 20]
nome_indici = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eva']
studenti_ = pd.Series(età_studenti, index=nome_indici)
print(studenti_)

Alice      20
Bob        22
Charlie    21
Diana      23
Eva        20
dtype: int64
